[build]
  command = "turbo run build --filter web"
  publish = "apps/web/dist"

[[redirects]]
  from   = "/api/*"
  to     = "https://api-production-3a6a7.up.railway.app/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
